//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MaxExporter.rc
//
#define IDD_MAIN_PANEL                  101
#define IDC_RADIO_COORD_SYSTEM_D3D      1001
#define IDC_RADIO_COORD_SYSTEM_OGL      1002
#define IDC_RADIO_COORD_SYSTEM_MAX      1003
#define IDC_EDIT_COMMAND                1004
#define IDC_CHECK_SUB_MESH              1005
#define IDC_EDIT_EXTERNAL_SKELETON      1006
#define IDC_CHECK_WORLD_SPACE           1007
#define IDC_RADIO_KEY_FRAME             1008
#define IDC_RADIO_ALL_FRAME             1009
#define IDC_CHECK_OPTIMIZE_SKELETON     1010
#define IDC_CHECK_GPU_SKINNING          1011
#define IDC_CHECK_GPU_LIGHTING          1012
#define IDC_CHECK_LIGHTMAP              1013
#define IDC_CHECK_LOW_LIGHTMAP          1013
#define IDC_EDIT_RENDER_ID              1014
#define IDC_CHECK_ENVMAP                1015
#define IDC_CHECK_LOW_ENVMAP            1015
#define IDC_CHECK_SHADOWMAP             1016
#define IDC_CHECK_LOW_SHADOWMAP         1016
#define IDC_RADIO_LOW_SIMPLE_LIGHTING   1017
#define IDC_RADIO_LOW_ADVANCED_LIGHTING 1018
#define IDC_CHECK_MEDIUM_LIGHTMAP       1019
#define IDC_CHECK_MEDIUM_ENVMAP         1020
#define IDC_CHECK_MEDIUM_SHADOWMAP      1021
#define IDC_RADIO_MEDIUM_SIMPLE_LIGHTING 1022
#define IDC_RADIO_MEDIUM_ADVANCED_LIGHTING 1023
#define IDC_CHECK_HIGH_LIGHTMAP         1024
#define IDC_CHECK_HIGH_ENVMAP           1025
#define IDC_CHECK_HIGH_SHADOWMAP        1026
#define IDC_RADIO_HIGH_SIMPLE_LIGHTING  1027
#define IDC_RADIO_HIGH_ADVANCED_LIGHTING 1028
#define IDC_CHECK_ULTRA_LIGHTMAP        1029
#define IDC_CHECK_ULTRA_ENVMAP          1030
#define IDC_CHECK_ULTRA_SHADOWMAP       1031
#define IDC_RADIO_ULTRA_SIMPLE_LIGHTING 1032
#define IDC_RADIO_ULTRA_ADVANCED_LIGHTING 1033
#define IDC_CHECK_EXTREME_LIGHTMAP      1034
#define IDC_CHECK_EXTREME_ENVMAP        1035
#define IDC_CHECK_EXTREME_SHADOWMAP     1036
#define IDC_RADIO_EXTREME_SIMPLE_LIGHTING 1037
#define IDC_RADIO_EXTREME_ADVANCED_LIGHTING 1038
#define IDC_RADIO_LOW_NONE_LIGHTING     1039
#define IDC_RADIO_MEDIUM_NONE_LIGHTING  1040
#define IDC_RADIO_HIGH_NONE_LIGHTING    1041
#define IDC_RADIO_ULTRA_NONE_LIGHTING   1042
#define IDC_RADIO_LOW_NONE_LIGHTING5    1043
#define IDC_RADIO_EXTREME_NONE_LIGHTING 1043

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1019
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
